### ISSUE TITLE
密钥指定-k 在你们后台看不到设备呢

### ISSUE THREAD

**Issue by kjcx** [pairmesh/pairmesh#33]
## Bug Report

密钥指定-k 在你们后台看不到设备呢

**Comment by vodkaslime** [comment]
请问你用的Github登录的还是微信登录的？
pairmesh binary是从我们的release下载的还是自己在本地编译的？
运行环境是什么？

**Comment by lonng** [comment]
你确定是连接的是我们的服务器吗？

**Comment by kjcx** [comment]
微信登录的 直接下载的release apple m1 
配置都需要配置什么

**Comment by kjcx** [comment]
用你们的后台需要配置这个吗
 export PAIRMESH_GATEWAY_API=<您的portal后端服务部署地址>
export PAIRMESH_GATEWAY_MY=<您的portal vue网站地址>
参数都是多少

**Comment by vodkaslime** [comment]
这两个是如果你想自己搭建pairportal这些用的。如果想直接使用pairmesh的话不需要specify这些。

你在启动pairmesh的时候log怎么说？

以及，试试启动sudo ./pairmesh不加-k，给出的log是什么？

**Comment by kjcx** [comment]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/17584149/160067794-6695dc93-2d4d-4776-b3e9-bf586fb23658.png">
2022-03-25T14:38:10.662+0800	INFO	Startup node successfully
2022-03-25T14:38:10.662+0800	INFO	Driver initialized successfully
加不加参数都是这2行就没了

**Comment by hi-windy** [comment]
@kjcx 现在你的托盘应该会多一个 PairMesh 的图标，我们现在打包的还是一个 mac 的 binary 我们最近会打包成标准的 Mac App。

**Comment by kjcx** [comment]
@hi-windy 可以了
