### ISSUE TITLE
Endpoint params for nodes

### ISSUE THREAD

**Issue by vodkaslime** [pairmesh/pairmesh#57]
## Feature Request

**Is your feature request related to a problem? Please describe:**
env variable is not reliable. MacOS and Windows have different ways of setting and handling env. And it's not a sustainable way of deploying to many users.

**Describe the feature you'd like:**
Let's YAML the nodes, just like how we YAML portal and relay

**Describe alternatives you've considered:**
N/A

**Teachability, Documentation, Adoption, Migration Strategy:**
N/A

**Comment by hi-windy** [comment]
I think use configuration for node is a bad idea because it will cause complexity. Prefer to use command line parameters.

For Linux: `./pairmesh -k <key> --api <api-server> --web <web-server>`

For Mac/Windows: Add a new configuration options to set the parameters.

**Comment by vodkaslime** [comment]
Ok makes sense. I'll get started from Linux since it's easier to implement and will benefit debugging & testing immediately. We can leave Mac/Windows part for later. They need more comprehensive design since UI experience is involved.
