### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ximply** [pairmesh/pairmesh#77]
## General Question

env：
CentOS Linux release 7.9.2009 (Core)
Linux 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 18:28:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

make error:
gofmt (simplify)
GO111MODULE=on CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build  -ldflags '-w -s -X "github.com/pairmesh/pairmesh/version.GitHash=a39b637" -X "github.com/pairmesh/pairmesh/version.GitBranch=master" ' -o bin/pairmesh ./cmd/pairmesh
cmd/pairmesh/main.go:17:8: //go:build comment without // +build comment
make: *** [pairmesh] error 1

**Comment by hi-windy** [comment]
@ximply PairMesh needs Golang compiler version greater than v1.17

**Comment by hi-windy** [comment]
@ximply Thanks for your feedback, I checked our README.md documentation and found nothing for Golang compiler version information.

It's helpful for others as well and can you file a pull request to fix this issue? 

I think the README.md `Quick Start` is a properly section for place this content.
