### ISSUE TITLE
Align current device information and connectivity status to the  right side

### ISSUE THREAD

**Issue by hi-windy** [pairmesh/pairmesh#82]
## Feature Request

![image](https://user-images.githubusercontent.com/78631691/161026537-dde2bff2-200b-4b6b-9040-efd1bcf8cf0a.png)

As title described, I think it's better to align device name information to the right side (the same as IP address).

**Comment by hi-windy** [comment]
@lingkeyang Are you interested in this issue?

**Comment by lingkeyang** [comment]
> @lingkeyang Are you interested in this issue?

Give me five.
